#!! DO NOT CHANGE ANYTHING BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING
# IF YOU ARE A USER DO NOT TOUCH THIS FILE

[env]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
monitor_speed = 115200
custom_firmware_version = 3.2.0
monitor_rts = 0
monitor_dtr = 0
monitor_filters =
    --echo
    --eol
	send_on_enter
	log2file
	time
	default
	esp32_exception_decoder
board_build.partitions = min_spiffs.csv
;build_unflags = -Os ; disable optimization for size
lib_compat_mode = strict
lib_ldf_mode = deep+
;115200 is used for compatability - if you are on windows and want the code to flash faster use 921600
upload_speed = 921600
lib_deps =
  	esp32-camera
	ESP32Async/ESPAsyncWebServer @ 3.6.0
	https://github.com/bblanchon/ArduinoJson.git
extra_scripts =
	pre:tools/customname.py
	post:tools/createzip.py
build_flags =
	; 下面将会注释掉所有与WiFi有关的参数
	; -DENABLE_ADHOC=${wifi.enableadhoc}            
	; -DADHOC_CHANNEL=${wifi.adhocchannel}
	; -DWIFI_CHANNEL=${wifi.channel}
	; '-DMDNS_HOSTNAME=${wifi.mdnsname}'
	; '-DWIFI_SSID=${wifi.ssid}'
	; '-DWIFI_PASSWORD=${wifi.password}'
	; '-DWIFI_AP_SSID=${wifi.ap_ssid}'
	; '-DWIFI_AP_PASSWORD=${wifi.ap_password}'
	; '-DWIFI_AP_CHANNEL=${wifi.adhocchannel}'
	#-DDEBUG_ESP_PORT=Serial
	'-DVERSION=""'                                     ; set the debug port
	
	'-DSERIAL_FLUSH_ENABLED=${development.serial_flush_enabled}'

	'-DOTA_PASSWORD=${ota.otapassword}'    ; Set the OTA password
	'-DOTA_LOGIN=${ota.otalogin}'
	'-DCAM_RESOLUTION=${cam.resolution}'

	-O2                    ; optimize for speed
	-DASYNCWEBSERVER_REGEX ; enable regex in asyncwebserver

	# 关于psram的配置，如果你使用的开发板没有psram，请注释掉下面三行，否则可能会出现系统启动错误
	-DBOARD_HAS_PSRAM             ; enable psram
	-std=gnu++17				  ; enable c++17
	-mfix-esp32-psram-cache-issue ; fix for psram

	; Compile with -DHTTP_PARSER_STRICT=0 to make less checks, but run faster
	-DHTTP_PARSER_STRICT=0
build_unflags = -std=gnu++11
