# This file is for user configuration

## !!Important note: Apostrophes inside of quotes ex: "a't" are NOT ALLOWED. This will fail to build!!

; 我会注释掉WiFi的信息，防止与我们的配网功能冲突，用户需要自己在我们的网页配置wifi信息
; [wifi]
; ssid = ""
; password = ""
; mdnsname = "Galeros-ESP32"
; channel = 1
; ap_ssid = "Galeros-ESP32"
; ap_password = "Galeros-ESP32"
; enableadhoc = 0
; adhocchannel = 1

; TOO: ota功能暂不修改，以后可能会改成配网功能的一部分，用户可以在网页上修改ota的登录信息和密码
[ota]
otalogin = "galeros"
otapassword = "Galeros-ESP32"

[development]
serial_flush_enabled = 0

[cam]
resolution = FRAMESIZE_240X240

